### ISSUE TITLE
[Feature Request] Edit Modifier Bucket Pop-Up

### ISSUE THREAD

**Issue by TheFabulousIronChef** [crnormand/gurps#304] opened 2021-02-14 12:54 UTC
Just GM'd my first game with FoundryVTT and GURPS Game Aid. It was a lot of fun. One area where I think it would be a great improvement and would really enhance speed of play is having GMs be able to modify the popup in the modifier bucket. There are quite a few things in there that we do not use (e.g., Feverish Defense in DFRPG) and others that come up frequently that aren't there. A workaround has been to create journal entries that have all of the modifiers from various tables in the DFRPG books. But that is somewhat time consuming to find. If GMs could edit the modifier bucket to have common modifiers (Bad footing, Deceptive Attack at a level higher than -1, etc.), that would be great. I know that I can write in the modifier and send it to a player, but anything that is preloaded is better. 

Thanks, as always--my players thought that the import feature and combat was really, really great. We had a good time.

**Comment by crnormand** [comment] 2021-02-16 18:02
Duplicate of https://github.com/crnormand/gurps/issues/165  (I linked your comment to that issue)

**Closed by crnormand** 2021-02-16 18:02 UTC
