### ISSUE TITLE
[it would be cool] Damage messaging system

### ISSUE THREAD

**Issue by gtludwig** [crnormand/gurps#348] opened 2021-03-01 17:28 UTC
Imagine the following scene:

Bog makes an attack and poor Goblin_1 fails to dodge. This means Bog's attack has landed and, to Goblin_1's despair, Bog rolls 2d6+5 cutting damage.

Then, the damage is dragged to Goblin 1's token and ADD pops up! The GM performs some ADD magic and clicks apply damage. Poor wee Goblin_1!

Still, this takes up precious time.

What if this flow would be slightly modified to:
1. The player that controls Bog selects the token of Goblin_1;
2. The player rolls for attack and the player that controls Goblin_1 is prompted for a defensive option;
3. If the attack succeeds, (optional) the player that controls Goblin_1 starts to cry, Bog is prompted to roll damage;
4. At this point, all the information regarding this attack is passed directly to the ADD:
- token_from; << Bog
- token_to; << poor wee Goblin_1
- hit_location; << torso (default) (for ranged attacks, this could default to 'random')
- damage_type; << cut
- damage_amount; << 17
- half_damage; << false
- follow_up; << "<empty>" or "<null>"
- other; << whatever other effects (i.e. +2 poison)
5. Goblin_1 token gets updated statuses;
6. The GM may opt to show the attack summary in the chat.

I understand this might be borderline automation, but I think it would be really cool!

**Comment by crnormand** [comment] 2021-03-01 17:39
You still get to keep the "[It would be cool]" tag... but this is sort of a duplicate of https://github.com/crnormand/gurps/issues/331

The whole idea is to speed up the damage resolution by delegating some of the work to the players (like targeting).    So I am going to close this issue, but reference it in the other.

**Closed by crnormand** 2021-03-01 17:39 UTC
