### ISSUE TITLE
[Improvement] Bucket - Highlight all-out attack and defense moves.

### ISSUE THREAD

**Issue by gtludwig** [crnormand/gurps#360] opened 2021-03-02 20:28 UTC
When the bucket modifier is open, it would be handy to highlight an all-out attack and all-out defense moves.

**Comment by crnormand** [comment] 2021-03-06 03:23
Effectively a duplicate of https://github.com/crnormand/gurps/issues/122

**Closed by crnormand** 2021-03-06 03:23 UTC
