### ISSUE TITLE
[Improvement] Token - apply status indicator when all-out attack or defense

### ISSUE THREAD

**Issue by gtludwig** [crnormand/gurps#361] opened 2021-03-02 20:38 UTC
A status token could be placed on the token that has taken an all-out attack or defense, a status indicator can be placed on the token until the next turn.

**Comment by crnormand** [comment] 2021-03-02 21:02
Yes... we definitely want to do this.  Unfortunately, this would use something called an Active Effect (which has duration, etc), versus the static effects we are currently using.... and this gets into the "automation" aspect of game play.

And we really don't know where SJG stands on this.   Although... if all we are doing is providing a 'notification', then maybe it would be ok.   And what I mean by this is that we never automatically add modifiers based on status.   They are only displayed in the modifier tooltip to remind the user that "the character is in shock", or is "lying prone", and the various modifiers that could be used.

An active effect would basically just be a "timer" on a status effect.   We would remind the player that the character took "such-and-such" a maneuver.  From a game standpoint, there really is no difference between an "all-out-defense" status and a "shock" status.   They would both provide reminders to the user (and show possible modifiers that could be applicable).

I am going to close this, because it is a duplicate of https://github.com/crnormand/gurps/issues/122

**Closed by crnormand** 2021-03-02 21:02 UTC
