### ISSUE TITLE
[Bug] Error on GCS re-import

### ISSUE THREAD

**Issue by LordOHelmet** [crnormand/gurps#1652] opened 2022-11-10 10:05 UTC
[Foundry stand alone V10 (288); GGA 0.15.8; no Mods; GCS 5.3.1]

I get the following error after trying to re-import a character.

![Chat error](https://user-images.githubusercontent.com/80178910/201061293-c0e34b28-52c3-4e97-9b4f-0e4433c36179.JPG)
![Console error](https://user-images.githubusercontent.com/80178910/201061309-c67bf58d-a44a-4078-b6a4-9ffc70c26da4.JPG)

To replicate: 
1. Creat a new character on GCS
2. Import it to Foundry
3. Create a new Foundry item
4. Drag the Foundry item on the new character
5. Re-import that character

**Comment by crnormand** [comment] 2022-11-10 14:54
Found it.    Again, a problem caused by the "data"->"system" rename in Foundry V10.   It will be in 0.15.9

**Closed by crnormand** 2022-11-10 14:54 UTC
