### ISSUE TITLE
inventory weight unit conversion

### ISSUE THREAD

**Issue by Frerol** [crnormand/gurps#502] opened 2021-04-12 22:00 UTC
The weight unit for the items in the actor's inventory aren't changing to kg (it's the standard unit for the brazilian edition) despite it being used as the default unit in the GCS sheet.
![image](https://user-images.githubusercontent.com/40567346/114468093-527f4d00-9bc1-11eb-880a-030c5d42c894.png)

**Comment by crnormand** [comment] 2021-04-12 22:14
Closing.   This issue is a duplicate of https://github.com/crnormand/gurps/issues/188 (which we haven't gotten to yet)

**Closed by crnormand** 2021-04-12 22:14 UTC
