### ISSUE TITLE
GM Rolls cannot be hidden in chat - FVTT 12 Stable 4 (Build 327) and GGA 0.17.2

### ISSUE THREAD

**Issue by Farmeroz** [crnormand/gurps#1914] opened 2024-06-16 07:28 UTC
GM Rolls cannot be hidden in chat - FVTT 12 Stable 4 (Build 327) and GGA 0.17.2 regardless of chat settings.

When setting chat to Private GM Roll, Blind GM Roll, or Self Roll (as GM), all chat output is public (clicking dice, clicking skills, damage, etc.

It *does* work if you use the /roll command, however.

**Comment by mjeffw** [comment] 2024-06-27 19:06
<img width="1329" alt="image" src="https://github.com/crnormand/gurps/assets/7349413/516a8fb1-5429-4751-af22-b963a05bf47d">

I can't reproduce this issue now. I wonder if when I fixed the Dice So Nice issue, it fixed this one as well? The Dice So Nice functionality was broken because of how we were creating ChatMessages.

**Comment by mjeffw** [comment] 2024-06-27 19:11
I'm closing this (for now). Let's reopen if it isn't fixed.

**Closed by mjeffw** 2024-06-27 19:11 UTC
