### ISSUE TITLE
Actor with an old condition icon breaks the canvas

### ISSUE THREAD

**Issue by Legendsmith** [crnormand/gurps#808] opened 2021-06-22 09:46 UTC
Got a game that migrated from an older versiona nd whenever I place an actor token that had the unconscious effect on it, this happens and the canvas breaks.
```js
Failed to load resource: the server responded with a status of 404 (Not Found)
dd-condition-unconscious.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
foundry.js:35290 Failed to load texture systems/gurps/icons/statuses/dd-condition-prone.png: Invalid URL
loadTexture @ foundry.js:35290
foundry.js:17467 Error: Invalid BaseTexture systems/gurps/icons/statuses/dd-condition-prone.png
    at loadTexture (foundry.js:35293)
    at async Token._drawEffect (foundry.js:44917)
    at async Promise.all (index 0)
    at async Token.drawEffects (foundry.js:44883)
    at async Token.draw (foundry.js:44532)
    at async Promise.all (index 3)
    at async TokenLayer.draw (foundry.js:19460)
    at async Canvas.draw (foundry.js:17464)
draw @ foundry.js:17467
foundry.js:35290 Failed to load texture systems/gurps/icons/statuses/dd-condition-unconscious.png: Invalid URL
```

**Comment by mjeffw** [comment] 2021-06-22 15:21
This was caused by the conversion of .png to .webp for all graphics files. We should really allow you to rerun the migration, but there's not an easy way to do that AFAIK.

You can clear the effects on a token with this script:
```js
let dae_effect = async function() {
  const effect_name = "Prone"; // Replace with the label of the effect to remove
  const effect = _token.actor.effects.contents;
  for (let i = 0; i < effect.length; i++) {
    let condition = effect[i].data.label;
    let status = effect[i].data.disabled;
    let effect_id = effect[i].data._id;
    console.log(`condition: [${condition}] status: [${status}] effect_id: [${effect_id}]`)
    if ((condition === effect_name) && (status === false)) {
        await _token.actor.updateEmbeddedDocuments("ActiveEffect", {"_id": effect_id, "disabled" : true});
    }
    if ((condition === effect_name) && (status === true)){
        await _token.actor.updateEmbeddedDocuments("ActiveEffect", {"_id": effect_id, "disabled" : false});
    }
  }
}

dae_effect();
```

**Comment by crnormand** [comment] 2021-06-22 16:05
Execute `/forcemigrate`.    This will re-run all of the migration functions, including the status icon rename.

**Comment by mjeffw** [comment] 2021-06-22 16:39
Just coming back to say that! ^^^^

**Comment by Legendsmith** [comment] 2021-06-23 00:01
Aah, I ran /forcemigrate earlier but without that token on the scene.

**Comment by crnormand** [comment] 2021-06-23 00:04
I am going to close this issue, since we already have the migration built in, and a chat command to enforce it.

**Closed by crnormand** 2021-06-23 00:04 UTC
