### ISSUE TITLE
[Feature Request] Vehicle Sheets

### ISSUE THREAD

**Issue by justinthejaguar** [crnormand/gurps#114] opened 2020-12-17 15:56 UTC
Would it be possible to add the option for vehicle actors into the GURPS system? My particular interest is in setting up space ships using GURPS Spaceships 4e.

**Comment by mjeffw** [comment] 2020-12-17 16:36
I will add it to the feature list, but we are focused on PC actors first.

**Comment by crnormand** [comment] 2020-12-17 17:09
The biggest issue is the display.   We would have to build a new HTML page to display the vehicle, and that takes time (especially since neither of us are web designers).    If you happen to have an HTML layout for a vehicle display, please send it to us.

**Comment by justinthejaguar** [comment] 2020-12-17 17:16
I will take a look around tonight for ideas, and maybe try to throw something together.

**Comment by crnormand** [comment] 2021-11-11 17:30
Duplicate of  https://github.com/crnormand/gurps/issues/1042

**Closed by crnormand** 2021-11-11 17:30 UTC
Labels: low priority
