### ISSUE TITLE
Journal Secrets not working (Launched in Safe Mode)

### ISSUE THREAD

**Issue by ChutterButter** [crnormand/gurps#1726] opened 2023-01-10 07:04 UTC
Hello! I have an issue around using secret text in the new v10 Journals. I have twice consulted the Foundry team and have been pointed to GGA as the culprit.

I am attempting to reveal info about important NPCs as the party learns more about them. However, when I click the "reveal" button, nothing happens. I confirmed this with a player account open in the browser. 

The secret text feature is documented here: https://foundryvtt.com/article/journal/

The issue persisted when I launched my world in Safe Mode. I am currently using the GURPS Game Aid as my system. I am on OSX and have tested this with a player in two Chromium based browsers. But the issue is on the GM side, the button does nothing when clicked.

<img width="960" alt="Screen_Shot_2022-12-29_at_10 48" src="https://user-images.githubusercontent.com/122344670/211483426-f47d1f07-784a-456b-a57d-ba1a882a4ef0.png">

Two individuals on the GURPS server also confirmed having issues with this feature.

**Comment by crnormand** [comment] 2023-01-10 16:27
I can duplicate, and when I take our Journal extension out, it works.   Now I have to figure out why our subclass is causing it to break.

**Comment by crnormand** [comment] 2023-01-10 22:53
I see where the problem is... and I have been posting on #dev-support and getting some answers.   I don't know yet if I have a good solution.

**Comment by ChutterButter** [comment] 2023-01-10 23:08
Thank you for the update Chris, I really appreciate it. The secrets feature
is perfect for a social adventure my group will be running, where they need
to collect gossip at a party that will give them hints on how to best
influence some key people.

**Comment by crnormand** [comment] 2023-01-10 23:18
Of course!   I think I have a solution, but it's pretty low level, so I'm worried that it might screw some other things up. So I'm going to test a lot more and if I'm lucky create a release later tonight or tomorrow.

**Comment by crnormand** [comment] 2023-01-11 03:56
Fixed in latest release.

**Closed by crnormand** 2023-01-11 03:56 UTC
