### ISSUE TITLE
Feature Request: Critical Rolls

### ISSUE THREAD

**Issue by Farmeroz** [crnormand/gurps#976] opened 2021-09-09 08:57 UTC
Allow a critical success/failure to generate a critical roll (3d6) to obtain a number for the tables.  Also, allow extension of critical success by the "7 on effective skill 20, 8 on effective skill 25" etc. (or really allow the progression to be set as desired).

**Comment by crnormand** [comment] 2021-11-15 05:40
Closing, as this seems a duplicate of https://github.com/crnormand/gurps/issues/993

**Closed by crnormand** 2021-11-15 05:40 UTC
