### ISSUE TITLE
User [name] lacks permission to update ActiveEffect [gibberish] in parent ActorData [different gibberish]

### ISSUE THREAD

**Issue by TheFabulousIronChef** [crnormand/gurps#2032] opened 2024-11-19 03:03 UTC
When our GM is doing stuff, we get a lot of this (all of the players get this, with their name substituting for "Vic"). Not even sure what to call this exactly, so I just tried to write an approximation of what's happening.  I say "When our GM is doing stuff" because I frankly am not sure what he was doing, although it may have been applying damage to an enemy, marking them defeated, or something like that. Probably at least tangentially involves the combat tracker. 

![image](https://github.com/user-attachments/assets/a486f5f1-8324-4543-a146-beccb68608f6)

**Comment by chrismaille** [comment] 2024-11-20 02:48
Duplicate of #2024

**Closed** 2024-11-29 18:00 UTC
