### ISSUE TITLE
[Bug] actor: calculate encumbrance weight mismatch

### ISSUE THREAD

**Issue by GuineaThePig** [crnormand/gurps#886] opened 2021-07-16 10:08 UTC
The "actor: calculate encumbrance" option never converts pounds to kg, so it will treat 30lbs as if they were 30kgs for the purpose of calculating encumbrance. This means characters are treated as if they were carrying double the weight. I'm using GCS for imports, not sure if that makes a difference
![cwb](https://user-images.githubusercontent.com/75427583/125931676-c948937b-4402-4dff-a699-ebe7cc95fa46.png)

**Comment by crnormand** [comment] 2021-07-19 22:29
Basically a duplicate of https://github.com/crnormand/gurps/issues/188.   We currently do not support metric weights.

**Closed by crnormand** 2021-07-19 22:29 UTC
