### ISSUE TITLE
[Feature Request] An easy way to change status icons

### ISSUE THREAD

**Issue by Boifuba** [crnormand/gurps#581] opened 2021-05-06 07:13 UTC
I would like to suggest an easy way to change the icons conditions. I know the commands are cool but we almost don't use things like muted or pinned. Could be more usefull something  showing if the token have or no defenses or any weird stuff... Someting i only want to work with less than 5 icons thans that amout of icons...

**Comment by crnormand** [comment] 2021-05-07 13:26
So you would like a user editable list of statuses?   So you can remove the ones you don't want to keep it to a more managable size?

Do you also want to add your own statuses?

**Comment by cefasheli** [comment] 2021-05-07 17:44
Yes! Exactly! I know it can kill some macro functionality. But depending on the adventure, some icons are useless

**Comment by cefasheli** [comment] 2021-05-07 17:45
There is a module called Combat Utility Belt that theoretically allows you to make these changes and even automate some things, but it does not seem to work with GGA properly

**Comment by mjeffw** [comment] 2021-09-07 23:42
Duplicate of #326.

**Closed** 2021-09-07 23:43 UTC
Labels: enhancement
