### ISSUE TITLE
Itens in journal!

### ISSUE THREAD

**Issue by cefasheli** [crnormand/gurps#296] opened 2021-02-10 19:08 UTC
Ok, my english is a waork in progress my i`ll try to explain it! 

I would like to suggest a change in itens. Theres doesn't have a spot to insert the weapons, armors data like RoF, Acc, pi, Imp etc.  COuld be very nice to be theses itens ready in journal to drag to sheets when the players wan to do it. 

Thanks very much!

**Comment by crnormand** [comment] 2021-02-10 20:34
Você fala português? Se sim, poste e @Gus pode traduzir.

**Comment by mjeffw** [comment] 2021-02-22 21:54
Duplicate of #328

**Closed by mjeffw** 2021-02-22 21:54 UTC
