### ISSUE TITLE
Extra resource that is uneditable

### ISSUE THREAD

**Issue by ssveter1** [crnormand/gurps#1833] opened 2023-07-14 20:16 UTC
Environment
GCS Version: GCS 5.13.0
GURPS 4e Game Aid (unoffical): 0.16.4
Foundry Version: V11 Patch 5 Build 305

Extra resource that is uneditable:

![image](https://github.com/crnormand/gurps/assets/10831302/2d10ea47-1c72-4374-96c4-46d76f3e95ca)

**Comment by stekman** [comment] 2023-07-23 20:57
My sheets have exactly the same. Also marking tokens with the red heart.

**Comment by TonyLinguini** [comment] 2023-08-23 16:35
Noticed this too, this seems to be for Impulse Points as referenced in Power-Ups 5. I don't know why it's made default here, and my current solution is just to remove this entry entirely from templates\actor\actor-sheet-gcs.hbs in the meantime
![image](https://github.com/crnormand/gurps/assets/82097109/2478435e-e231-4617-ab88-73c8ef698113)

**Comment by mjeffw** [comment] 2024-01-07 19:24
This appears to  be caused by a global rename someone did. (This resource tracker is really just the HP tracker, with "HP" renamed to "IP".) It doesn't seem to be an issue any more. I'm closing this issue, but let me know if it reoccurs.
@TonyLinguini @stekman @ssveter1

**Closed by mjeffw** 2024-01-07 19:24 UTC
