### ISSUE TITLE
Add @target to /status (or other OTF) commands

### ISSUE THREAD

**Issue by ssveter1** [crnormand/gurps#1646] opened 2022-11-01 18:05 UTC
Enable @target for use with OTFs
For example: [/st +stun @target]
or [“Cast”/if [Sp:"Strike Blind”] {!/if [HT-@margin\\/st +blind @target]}}]

**Comment by crnormand** [comment] 2022-11-10 15:22
I would like to expand the list of things that support @target, however, that brings up a permission issue,

Normally, players are not allowed to "edit" the values of another player's character, because they don't have ownership.   And yes, setting a status on a token, is "editing".   

So while it IS possible to build a system where this will work (by secretly sending a message to the GM's client, and having the GM's client make the change silently), it is a bit of work.     

ALSO, this would allow players to set statuses on NPCs and other PCs.    Of course, we could just make this a GM only feature.

**Comment by crnormand** [comment] 2022-11-10 16:36
Actually, I am closing this because it is a duplicate of https://github.com/crnormand/gurps/issues/1646

**Closed by crnormand** 2022-11-10 16:36 UTC
Labels: enhancement
