### ISSUE TITLE
[Bug] The DR Advantage as Imported from GCA is Wonky

### ISSUE THREAD

**Issue by engurrand** [crnormand/gurps#865] opened 2021-07-06 03:03 UTC
There are two obvious issues, possibly others, when importing a character with the DR advantage, assuming that character was made with GCA:

1. The DR Advantage does not protect Arms, Legs, or Vitals. It appears GCA's names for those locations do not match the names used in Foundry? 
2. The DR Advantage lists as text "0 - X" where x is the value granted by your DR advantage and 0 is listed for every hit location except the skull, which lists 2. This is perfectly human-readable but the damage parser doesn't seem to know what to do with it.
I've attached two examples.

![DR values imported from GCA](https://user-images.githubusercontent.com/80167921/124535993-ba1df080-dddc-11eb-8ca1-72597fd3ce7a.JPG)

[Characters with armor.zip](https://github.com/crnormand/gurps/files/6767051/Characters.with.armor.zip)

**Comment by crnormand** [comment] 2021-07-06 18:20
So the issue is that the GCA export is providing that string "0 + 8" as the DR value.    Here is the XML output:
```
<protectionlist>
<bodyplan type="string">Humanoid</bodyplan>
<id-00001>
<location type="string">Eyes</location>
<dr type="string">0 +8</dr>
</id-00001>
```

So the question becomes, do I try to fix the GCA export, or modify the Javascript import code to "collapse" that equation into the number 8?

**Comment by crnormand** [comment] 2021-07-06 18:22
Oh, and as to the hitlocation names... yeah, GCS and GCA do not use the same names.   We have done our best to converge them, but there is only so much we can do.

**Comment by crnormand** [comment] 2021-07-06 20:02
I decided to implement the fix in our import code (instead of yet another version of the GCA export script).  

Also, I found the bug I introduced in the HitLocation name matching... and it will now correctly interpret "Arms" as "Left Arm" and "Right Arm".   It will be in the next release.

**Closed by crnormand** 2021-07-06 20:02 UTC
Labels: bug

**Comment by engurrand** [comment] 2021-07-06 20:04
Ur a wizard, Mr. Normand.
